### PR TITLE
hieradata: Prepare for jQuery UI 1.14

### PR DESCRIPTION
**Pull request by mgol**

### CODE REVIEW

**Review by Krinkle — APPROVED** [review]

**Comment by mgol** [comment]
Everything looks fine on staging: https://stage.api.jqueryui.com/1.13/. In production, though, it seems the other `jquery-wp-content` PR (https://github.com/jquery/jquery-wp-content/pull/460) made the 1.14 structure already present but with the 1.13 site empty: https://api.jqueryui.com/1.13/. I'll merge this to `production` as well and I hope it'll generate the sub-site for 1.13 then.

**Comment by mgol** [comment]
Oh, actually, on staging the 1.13 home page is fine but there are no categories on the left side. I wonder if I need to create a new tag on `1-13` to kick-start the process...

**Comment by mgol** [comment]
The structure appeared after merging this to `production`. I now pushed a tag `v1.13.8` to see if the categories list generates properly.

**Comment by mgol** [comment]
BTW, I'm talking about categories, but all the pages are missing, including entries like https://api.jqueryui.com/1.13/addClass/.

FWIW, when I pushed a tag to the `1-13` branch, staging was updated properly and e.g. https://stage.api.jqueryui.com/1.13/addClass/ loads fine.

Some time has passed since I pushed the tag and production is still empty for 1.13, though... 🤔

**Comment by Krinkle** [comment]
Puppet has applied the change to the builder.

```
$ ssh builder-02.ops.jquery.net 
…
krinkle@builder-02:~$ sudo journalctl -u puppet -n100 -f
…
Jul 19 19:05:52 builder-02 puppet-agent[2828424]: Applied catalog in 3.29 seconds
Jul 19 19:35:50 builder-02 puppet-agent[2828646]: (/Stage[main]/Ssh::Server/Ssh::Server::Ca_signed_hostkey[/etc/ssh/ssh_host_rsa_key-cert.pub]/File[/etc/ssh/ssh_host_rsa_key-cert.pub]/content) content changed '{sha256}e1f970ea7a7e991e6754fe3a712aca4836a0d9e5d631858647e0727afdf4a0a2' to '{sha256}9a1ba73d08cf9025660ec848b0d2a3b5d1bfa23c566a81d8008093306e8f45cf'
Jul 19 19:35:50 builder-02 puppet-agent[2828646]: (/Stage[main]/Ssh::Server/Ssh::Server::Ca_signed_hostkey[/etc/ssh/ssh_host_ecdsa_key-cert.pub]/File[/etc/ssh/ssh_host_ecdsa_key-cert.pub]/content) content changed '{sha256}081a67f61f75a6db10bb0fff32f2247811b8df43d02bee48e1c48d0daf534d43' to '{sha256}90e9a6dc7e9b943eae16b86cfeb14784d345855b7415954d80ccd8e9106c835a'
Jul 19 19:35:50 builder-02 puppet-agent[2828646]: (/Stage[main]/Ssh::Server/Ssh::Server::Ca_signed_hostkey[/etc/ssh/ssh_host_ed25519_key-cert.pub]/File[/etc/ssh/ssh_host_ed25519_key-cert.pub]/content) content changed '{sha256}057791a949fd99c89e74f100a40e578b4f7b470702c39d780ae094e7e158cc37' to '{sha256}9106e5f20183df3139c6bfb7648bdc483fe75a2dae0580545e63f669be4e77bc'
Jul 19 19:35:51 builder-02 puppet-agent[2828646]: (/Stage[main]/Ssh::Server/Service[sshd]) Triggered 'refresh' from 3 events
Jul 19 19:35:53 builder-02 puppet-agent[2828646]: Applied catalog in 3.19 seconds
Jul 19 20:05:53 builder-02 puppet-agent[2828811]: Applied catalog in 3.41 seconds
…
```

Looking at the working directory:

```
krinkle@builder-02:/srv/builder/api_jqueryui_com_1_13$ sudo -u builder git show     
commit dcbd8daa74cf62702c27fa15f5c9bf368513772c (HEAD -> 1-13, tag: v1.13.8, origin/main, origin/HEAD, origin/1-13)
Author: Michał Gołębiowski-Owczarek <m.goleb@gmail.com>
Date:   Sun Jul 21 01:24:13 2024 +0200

    1.13.8
```

Looking at the notifier, note that your added YAML entry for the 1-13 subsite, like the other subsites, simply following the branch in both staging and prod. The branch+tags is currently set on the main site only. We don't currently have extra tags overhead and separation in the new infra, as changes are less frequent there. Tag restriction could be set there, if you like, in the same way. At the moment, the system "should" build on commits instead.

```
krinkle@builder-02$ cat /etc/notifier.d/builder-api_jqueryui_com_1_13.js
module.exports = function( server, exec ) {
  server.on( "jquery/api.jqueryui.com/push/heads/1-13", exec );
```

So what events has the notifier processed recently?

```
journalctl -u notifier -n10000 | grep -E 'COMMAND|grunt deploy|Done'
…
Jul 20 02:04:09 builder-02 sudo[2832531]: notifier : PWD=/usr/local/share/notifier ; USER=builder ; COMMAND=/usr/bin/git -C /srv/builder/releases_jquery_com fetch -v origin
Jul 20 02:04:10 builder-02 sudo[2832540]: notifier : PWD=/usr/local/share/notifier ; USER=builder ; COMMAND=/usr/bin/git -C /srv/builder/releases_jquery_com merge --ff-only 881d1d71f5a126a69536c2cb94195cdbc2d8e4bd
Jul 20 02:04:10 builder-02 sudo[2832563]: notifier : PWD=/usr/local/share/notifier ; USER=builder ; COMMAND=/usr/local/bin/builder-do-update /srv/builder/releases_jquery_com
Jul 20 02:04:21 builder-02 node[795228]: [notifier-server:script:builder-releases_jquery_com.sh] + node_modules/.bin/grunt deploy
Jul 20 02:04:35 builder-02 node[795228]: [notifier-server:script:builder-releases_jquery_com.sh] out Done.
Jul 20 02:04:35 builder-02 node[795228]: [notifier-server:script:builder-releases_jquery_com.sh] + node_modules/.bin/grunt deploy
Jul 20 02:04:51 builder-02 node[795228]: [notifier-server:script:builder-releases_jquery_com.sh] out Done.
Jul 20 02:04:52 builder-02 node[795228]: [notifier-server:script:builder-releases_jquery_com.sh] out Done!
Jul 20 23:24:23 builder-02 sudo[2847390]: notifier : PWD=/usr/local/share/notifier ; USER=builder ; COMMAND=/usr/bin/git -C /srv/builder/api_jqueryui_com fetch -v origin
Jul 20 23:24:24 builder-02 sudo[2847399]: notifier : PWD=/usr/local/share/notifier ; USER=builder ; COMMAND=/usr/bin/git -C /srv/builder/api_jqueryui_com merge --ff-only 750719b46eb97a81f6661bd6585cae2b9febe9f4
Jul 20 23:24:24 builder-02 sudo[2847402]: notifier : PWD=/usr/local/share/notifier ; USER=builder ; COMMAND=/usr/local/bin/builder-do-update /srv/builder/api_jqueryui_com
Jul 20 23:24:32 builder-02 node[795228]: [notifier-server:script:builder-api_jqueryui_com.sh] + node_modules/.bin/grunt deploy
Jul 20 23:24:47 builder-02 node[795228]: [notifier-server:script:builder-api_jqueryui_com.sh] out Done.
Jul 20 23:24:48 builder-02 node[795228]: [notifier-server:script:builder-api_jqueryui_com.sh] + node_modules/.bin/grunt deploy
Jul 20 23:25:02 builder-02 node[795228]: [notifier-server:script:builder-api_jqueryui_com.sh] Done.
Jul 20 23:25:02 builder-02 node[795228]: [notifier-server:script:builder-api_jqueryui_com.sh] out Done!
```

@mgol My guess is that the branch hasn't received a commit yet since deploying the puppet change to production.

To be sure you could verify the timing at https://github.com/organizations/jquery/settings/hooks. I suggest either using the hooks admin page on GitHub to find the "1-13 branch commit" event under builder-02, and replay it (it would have been ignored before the puppet change to listen for it). Or, push a no-op commit to the branch.

**Comment by mgol** [comment]
It'd be great if new sites deployed from the latest commit on the branch or the latest matching tag so that noop commits or tags were not required. I'll push a noop commit later to the `1-13` branch.

EDIT: I pushed a dummy commit (just a new tag) and it worked, indeed.

**Comment by mgol** [comment]
I pushed a dummy commit (just a new tag) and it worked, indeed.

**Pull request merged**
